example/src/index.js
lib/number_format.js
src/number_format.js
test/input_test.js

This PR fixes [issue #37](https://github.com/s-yadav/react-number-format/issues/37)

Fix decimalPrecision with custom decimalSeparator

---

src/number_format.js

Sorry I have to format your code and add some prop validation in order to use it as per my project
1. Added new prop as allowNegative
2. If allowNegative and you enter '-' anywhere in the input it will add '-' before the prefix
3. If you enter '-' second time and if number is already negative it will remove '-'

Initial commit for negative number support

---

package.json
src/number_format.js

This add the `prop-types` package and migrates the import from React to the prop-types package.

Migrate deprecated PropTypes

---

src/number_format.js
test/library/keypress_and_caret.spec.js
test/test_util.js

This bug appears on OSX Safari and Chrome, at least. Ref https://bugs.chromium.org/p/chromium/issues/detail?id=779328
v3 now corrects focus caret position, but relies on `event.target.selectionStart`, which is not immediatelly available due to this bug. The reported value is always `0` instead of mouse position. 
This PR offers a workaround to avoid caret position reset, until browser vendors push a fix,  and is based on `v3` branch:
- Add a test to fail on this bug
- Wrap `onFocus` event handler in a `setTimetout(0)`
- Fix other on focus test to work with async behaviour
Other fix: 
- Small naming typo fix (`caretPosition`)

Fix onFocus caret reset position bug

---

src/number_format.js
test/test_util.js

When formatted value doesn't equal to the last one, `onBlur` callback is invoked in an asynchronous way. In this case according to [documentation](https://reactjs.org/docs/events.html#event-pooling) the event needs to be persisted to allow references to the event to be retained by user code.

Fix an issue with accessing blur event's properties

---

README.md

The mask prop default value is misleading in the readme. The actual code uses a single space as default value, and pads out missing chars with space char.
If I want to get rid of the white spaces I have to set it to an empty string.

Fixed mask prop default value documentation

---

src/number_format.js

This pull request addresses the following issues:
- When doing parseFloat(numAsString) and parseFloat(lastNumStr) on empty strings, it will return NaN. NaN !== NaN is true, so setState gets called continuously when you first click on an input. This causes and infinite loop and crashes the React App.
- onValueChange does not get called when removing a '-' sign using backspace. This prevents the parent component from updating it's state to use the new value. If the number-format component value prop is tied to this state it will block the '-' sign from being removed.
All tests are passing for this PR, but I would recommend writing tests for these cases.
My components look like this, using Material UI:
```
<TextField
label="Total"
value={valueFromRedux}
onChange={values => { …
```

Infinite update loop + call onValueChanged when '-' removed fix 

---

src/utils.js
test/library/input_numeric_format.spec.js

I used a component similar to the following:
```
<NumberFormat
value={this.state.value}
isNumericString
onValueChange={({value}) => this.setState({value})}
decimalScale={2}
/>
```
And the combination of isNumericString and decimalScale props caused bug with entering negative number. When I entered minus sign, input immediately showed "-0" and this zero could not be removed using backspace.

Fix input of negative number in case of isNumericString & decimalScale

---

typings/number_format.d.ts
typings/number_format.spec.tsx

Hey @s-yadav, thanks for adding types to this library. 
There is a problem when using default input props like `readOnly` or `autoFocus` because the type is extending `HTMLAttributes` and not `InputHTMLAttributes`.
I have added a small test case too, don't know if I should expand it.

Typescript: Allow using native Input props

---

src/number_format.js

Object.assign isn't transformed when published on NPM. It's doesn't work with IE 11 nor with Chrome 41, the engine used by the Google crawler.

Fix IE 11 issue

---

package.json

Hi,
You were building an esm module without specifying it in the package.json for module bundler (like Webpack). I added the required field and now apps that support it will point to the .es file instead of the umd.

Add module field to package.json for module bundler

---

src/number_format.js

We are using material ui text inputs and need the ability to programmatically trigger focus on the custom input. This adds this capability and I wasn't sure if there was a reason this wasn't propagated to custom inputs. I also wasn't sure what is easiest for you associated to the library. I didn't submit this pull request with the built resources but if you would like that let me know and I will compile it and commit that. Thanks for the number format library!

Adds getInputRef to the CustomInput

---

README.md
example/src/index.js
src/number_format.js
src/utils.js
test/library/input_numeric_format.spec.js

@s-yadav I reviewed the code regarding not applying the thousandSeparator when the number is zero.  It din't appear to exist so I added it for you. Thanks!

Add allowLeadingZeros property.  Bypass applying thousandSeparator when left side of decimal is zero

---

README.md
example/src/index.js
src/number_format.js
test/library/input.spec.js

When defined, this prop defines which keys to accept as decimal
separators. This is useful in cases where users might want to enter both
comma and dot as separators
Related issues: #324, #133, #223, #261

Add `allowedDecimalSeparators` prop

---

src/number_format.js

If getInputRef is noop by default, a ref is given to the customInput, when used. 
Causing a ugly warning in React.

getInputRef should not be default noop

---

README.md

Because there is a `yarn.lock` and no `package-lock.json`, it's better for developers to use Yarn as a dependency management tool.
I've updated the README.
Also, I didn't know if I should change the `npm` commands too, for example
- `npm start` > `yarn start`
- `npm run bundle` > `yarn bundle`
What's your opinion on this ?

Suggest to use Yarn for dependencies

---

typings/number_format.d.ts

In my previous PR (https://github.com/s-yadav/react-number-format/pull/345) I added a new prop but no new typing for it. Oops.

Add missing typescript typings

---

typings/number_format.d.ts

This value can be set explicitly to `undefined`, e.g. when the user clears the field:
https://github.com/s-yadav/react-number-format/blob/b233bd68c7cd16c63287c3aa4df576c2ff80eca9/src/number_format.js#L225

Reflect possible undefined floatValue in typings

---

src/number_format.js
test/library/input_numeric_format.spec.js

Fixed issue with dot separator when decimalScale is set to zero #375

---

src/number_format.js
test/library/keypress_and_caret.spec.js

`onFocus` is handled asynchronously with setTimeout. When testing inputs with react-number-format, it prints a warning saying it is updating the unmounted component.
Clear focusTimeout on unmount.

fix: Clear focusTimeout timeout on unmount

---

README.md

Corrects the default value of `allowEmptyFormatting` to false (see [here](https://github.com/s-yadav/react-number-format/blob/master/src/number_format.js#L75))

Correct allowEmptyFormatting default value in README

---

src/number_format.js
test/library/format_as_text.spec.js
test/library/input.spec.js

This PR is an incremental PR against #347 based on this [comment](https://github.com/s-yadav/react-number-format/pull/347#issuecomment-683865867)

Incremental PR towards #347

---

typings/number_format.d.ts

Pretty trivial PR, but since you need to be able to set the `value` prop to `null`, seems like it should be allowed in the typings.
That said, the behavior itself did confuse me. [This line specifically](https://github.com/s-yadav/react-number-format/blob/master/src/number_format.js#L142), where you ignore the `value` prop if it is `undefined`....  I guess you are using `value={undefined}` as a signal from the consumer that they want the NumberFormat to be stateful?
Might be better to have an explicit `stateless` prop. But maybe there's just some inevitable confusion when you can use the same component in either way.
I could add a bit to the readme about passing `null` if you are trying to use the NumberFormat as a stateless component.

Allow null value in TypeScript typing

---

README.md

This PR adds the documentation for the max value use-case for input fields.
https://codesandbox.io/s/react-number-format-isallowed-8gu0v

Add example for max value use-case

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This PR fixes the PR & Issue template formatting to use less strong headers to help with readability

Fix PR & issue template formatting

---

src/number_format.js
test/library/input.spec.js

When the input gets value via the auto-complete feature of a browser and is `allowEmptyFormatting` is allowed, it does not show the updated value and shows the old formatted string.
Browser autocomplete replacing the whole value will not update the input field with the new value
The logic looks to validate if the selection is for the entire string and updates the value 
#450 
No change in the usage

Fix full value replacement issue when allowEmptyString is set to true 

---

src/number_format.js
test/library/input.spec.js

This adds a test case for hotfix PR: #516 
No core changes. Just adds a test case
#516

Add test case for full value replacement if the new value is the same as the last number of the previous value

---

README.md

The [docs](https://github.com/s-yadav/react-number-format/blob/master/README.md) show a wrong example of the `isAllowed` callback. It returns the `inputObj` if it passes the check or `undefined`. This actually works in JavaScript because of type coercion (IMO still a bad practice). However, in TypeScript the type definition enforces a `boolean` to be returned.
```javascript
const MAX_VAL = 1400;
const withValueLimit = (inputObj) => {
const { value } = inputObj;
if (value < MAX_VAL) return inputObj;
};
<NumberFormat value={12} isAllowed={withValueLimit} />;
```
The [type definition](https://github.com/s-yadav/react-number-format/blob/master/typings/number_format.d.ts) requires a `boolean`:
```typescript
isAllowed?: (values: NumberFormatValues) => boolean;
```
Aligned the `isAllowed` …

Align Docs Is Allowed Example With Type Definition

---

package.json
src/utils.js
test/library/input.spec.js

This fixes the trailing zeros issue when an input like `###.00` is provided
N/A
- Should show the right number of zeros in all cases based on the `decimalScale` provided
- Adds a function to identify if the string is all zeros
- Uses that conditionally to pass the value to `limitToScale`
Issue: #533 
```
<NumberFormat
name={"AmountCents"}
value={"100.00"}
thousandSeparator
prefix="$"
decimalScale={2}
isNumericString
/>
```
Output: 100.00

Fix issue #533

---

src/number_format.js

In a huge app (my application has some 40+ controls and form management is done using Formik) and type some data in the react-number-format control and hit 'tab'/ go to some other control, then the focus goes back to the previous control this can be seen by entering a huge huge number in the example or a very small number in the huge app.
Debugged the issue and it narrowed down this line where the setTimeout execution was late so clearing this on blur and on unmount of the component to avoid a memory leak.
There was no such issue raised
Type a huge huge number in the example app and hit 'tab' to observe the issue

fix: input refocused after blur

---

.gitignore
README.md
src/number_format.js
src/utils.js

The issue https://github.com/s-yadav/react-number-format/issues/481 was not properly resolved with [this change](https://github.com/s-yadav/react-number-format/blame/14208b6e71d0c3e36a13415a073d3a08f0ea1318/src/number_format.js#L1011
). The error still exists when using `NumberFormat` on the server.
PS: can we merge and deploy this please as soon as possible? This is a release blocker for us at the moment. Thanks for your help. Let me know what it takes to get this done anytime.
I do not have one, sorry.
Use `NumberFormat` on the server.
Tests the `typeof navigator` which ensures the code will not fail on the server. The current check did catch all cases.
--> see https://github.com/s-yadav/react-number-format/pull/560/commits/b0735ef75e8517dc476795f71d5992485e95721e
resolves …

fix: fixed SSR issue (w/ navigator) when using together with @react-pdf/renderer

---

README.md
example/src/index.js
src/number_format.js
test/library/input.spec.js
typings/number_format.d.ts

added support for Custom numeral which automatically formats it to standard English numeral based on suggestion made on my [previous pull request](https://github.com/s-yadav/react-number-format/pull/535#issuecomment-849824452) 
added an optional prop customNumerals which accepts an array of custom numbers ranging from 0 to 9,
eg: customNumerals={['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹']} which is persian numeral for 0-9
- [ x] Chrome
- [ x] Chrome (Android)
- [x ] Firefox

feat: added custom numeral support

---

README.md
src/number_format.js
test/library/input.spec.js
test/library/input_numeric_format.spec.js
typings/number_format.d.ts

This PR adds a source object in the `onValueChange` function which returns the event object and the source of the trigger
API change for `onValueChange` to allow getting the source details and the event object
Issue: #587 
```
<NumberFormat
value={this.state.profit}
thousandSeparator={true}
prefix={'$'}
onValueChange={(values, sourceInfo) => {
const { formattedValue, value } = values;
// Event is a Synthetic Event wrapper which holds target and other information. Source tells whether the reason for this function being triggered was an 'event' or due to a 'prop' change
const { event, source } = sourceInfo;
}}
```

feat: Add source details in onValueChange

---

src/number_format.js
test/library/input.spec.js

Sharing 'format' and 'customNumerals' props does not allow to enter symbols from the 'customNumerals' array.
Below i use your function getNumberRegex for get correct regular expression

fix: get correct regular expression to sharing 'format' and 'customNumerals' props

---

typings/number_format.d.ts
typings/number_format.spec.tsx

We are using react-number-format together with material-ui. In our case we want to use the custumInput "TextField" but pass the prop: `{ size: "small" }`.
When we do this we get the error:
```
No overload matches this call.
Overload 1 of 2, '(props: NumberFormatProps | Readonly<NumberFormatProps>): NumberFormat', gave the following error.
Type 'string' is not assignable to type 'number | undefined'.
Overload 2 of 2, '(props: NumberFormatProps, context: any): NumberFormat', gave the following error.
Type 'string' is not assignable to type 'number | undefined'.ts(2769)
```
The problem here is, that `NumberFormatProps` are typed to always extend `InputAttributes`. Where actually when we use a customInput there is no reason to pass `InputAttributes`. In that case we should be able to pass the …

feat: make typings for customInput generic

---

package.json

This should enable webpack and other bundlers to only import used functions and components.

Mark module as side effect free

---

src/types.ts

Currently the type of `event` that `SourceInfo` has is `SyntheticEvent` with no type argument. In the implementation, I believe that it is the `input` element that fires the event, so `SyntheticEvent<HTMLInputElement>` should be more appropriate here. This change will improve integration with other libraries such as MUI in terms of TypeScript types.
https://github.com/s-yadav/react-number-format/blob/master/src/types.ts#L23
befor: `SyntheticEvent`
after: `SyntheticEvent<HTMLInputElement>`

Pass type parameter to SyntheticEvent

---

documentation/v5/docs/numeric_format.md

add missing prop (`fixedDecimalScale`) to docs
update to documentation
fixes #734

Add fixedDecimalScale to numeric format docs

---

documentation/v5/docs/numeric_format.md
documentation/v5/docs/pattern_format.md
documentation/v5/docs/props.md
example/src/index.js
package.json
src/number_format_base.tsx
src/numeric_format.tsx
src/pattern_format.tsx
src/types.ts
src/utils.tsx
test/library/input.spec.js
test/library/input_numeric_format.spec.js
test/library/keypress_and_caret.spec.js
test/test_util.js
test/types/number_format.spec.tsx
yarn.lock

- Optimize rendering, and avoid multiple rerender when number format is mounted. 
- Try to guess valueIsNumericString based on props and value, so the user no longer has to define this prop, if the format prop (prefix, suffix, format) doesn't have the number in it.
- Fixes #736 - Fix for focus on mount getting reset.
- Fixed #740 - fixed type for the format, removeFormat, getCaretBoundary.
- Fixed #741 - Thousand and decimal formatting broken while typing when value isNumericString is set to false
- Fixed #742 - cursor position getting changed when format props are updated during typing.
- Fixed #725 - The cursor position not being correct when allowed decimal separator is typed
- Fixed a couple of false positive tests and some regressions around those.
- move caret position test to …

Optimize render

---

src/number_format_base.tsx

closes: https://github.com/s-yadav/react-number-format/issues/760
See issue for more context

fix(number_format_base): prevent warnings in SRR when using useLayoutEffect.

---

documentation/v5/docs/customization.md

Edited the customization.md with an example how to write an IBAN input field

Add IBAN input field customization example

---

src/number_format_base.tsx

This change is based on https://stackoverflow.com/a/66086044 `currentTarget`:  only exists if used right from the `onFocus` event; but we get currentTarget **null** because `onFocus(e)` is called **within** a timeout.
References:
- https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget#currenttarget_versus_target
- https://github.com/adobe/react-spectrum/blob/9d8c74a344c9b7539f00fa58d0a02b062b6e830e/packages/%40react-aria/interactions/src/useFocus.ts#L64

fix: pass currentTarget to onFocus

---

src/number_format_base.tsx

Fixes #811
I'm opening this PR as an attempt to resolve `jest` + `testing-library` issue reported in #811.
I have an open question on that issue https://github.com/s-yadav/react-number-format/issues/811#issuecomment-1819527005 where I wondered why `el.selectionStart !== el.selectionEnd` existed; but after a lot of thinking I cannot see a reason for it
`selectionStart` and `selectionEnd` will always be the same when the caret is placed and nothing is selected:
https://github.com/s-yadav/react-number-format/assets/9648559/fb3c2791-9e43-40c8-b358-91d4a2cb85ac
so `el.selectionStart !== el.selectionEnd` will ***only*** happen if the user have text selected:
https://github.com/s-yadav/react-number-format/assets/9648559/9ff9066c-de30-4c83-ba8f-a1b2bd6fb690
which differs from the intention …

fix: `setCaretTimeout` checks

---

src/number_format_base.tsx

- `updateValueAndCaretPosition` is used only once
- its params `setCaretPosition` and `caretPos` were always set to something static
- `setCaretPosition: true`
- `caretPos` not passed, hence `undefined`
This PR removes these 2 params; and removes unnecessary checks
**Note:** not sure if these params were used for different purposes in the past, or if they are planned to used differently in the future, but they are not used as of right now, so I'm removing them.

refactor: clean up `updateValueAndCaretPosition`

---

documentation/v5/docs/numeric_format.md
documentation/v5/docs/props.md

The documentation is missing the thousandSeparator prop in the custom input, causing confusion.

- Fix thousandSeparator missing from documentation

---

.github/workflows/CI.yml

* Update node version.
* Use the latest versions of setup-node and checkout actions.
* Use `--frozen-lockfile` flag when running `yarn install`.
* Update script to run the new test suite.

Update CI action to run the new test suite

---

src/number_format_base.tsx
test/library/input.spec.jsx

`onValueChange` is not called for values with 3 or less characters.
[The problem is better described in this issue's discussion.](https://github.com/s-yadav/react-number-format/issues/812)
https://codesandbox.io/p/sandbox/numeric-number-format-on-value-change-bug-qrgj2h?file=%2Fsrc%2FApp.tsx
I have removed one of the tests because it doesn't seem to be very meaningful. In the PR's diffs, I have elaborated it in further detail.
This pr aims to fix the issue by simplifying the `useEffect`'s condition which is responsible for ensuring `onValueChange`'s callback is invoked.
https://github.com/s-yadav/react-number-format/issues/812
n/a
n/a

fix: `onValueChange` not called for values with 3 or less characters

---

src/numeric_format.tsx
src/pattern_format.tsx

The return type of `NumericFormat` and `PatternFormat` was being inferred as `JSX.Element` which caused the following type errors (`typescript` `v5.7.3` and `@types/react` `v19.0.4`):
```
[redacted] - error TS2786: 'NumericFormat' cannot be used as a JSX component.
Its type '<BaseType = InputAttributes>(props: NumericFormatProps<BaseType>) => Element' is not a valid JSX element type.
Type '<BaseType = InputAttributes>(props: NumericFormatProps<BaseType>) => Element' is not assignable to type '(props: any) => ReactNode | Promise<ReactNode>'.
Type 'Element' is not assignable to type 'ReactNode | Promise<ReactNode>'.
Property 'children' is missing in type 'Element' but required in type 'ReactPortal'.
58             <NumericFormat
~~~~~~~~~~~~~
node_modules/@types/react/index.d.ts:387:9
387 …
```

fix: add explicit return types
