s-yadav/react-number-format

custom_formatters/card_expiry.js, example/src/index.js, src/number_format.js
Hi! Thank you for the component. I want to help with #77
=> Fix linter warnings. Fixes #77

README.md, package.json, typings/number_format.d.ts, typings/number_format.spec.tsx, typings/tsconfig.json, yarn.lock
- added typings for NumberFormat component for better Typescript experience
- added types property in package.json for tsc to recognize declaration file
- updated README to use default import as the library is using module.exports
=> added typings for NumberFormat component

lib/number_format.js, src/number_format.js, test/library/keypress_and_caret.spec.js, test/test_util.js
Relates to issues #149 and #211.
=> Don't reset caret when tabbing into a field

typings/number_format.d.ts
=> `onValueChange` has only one argument

typings/number_format.d.ts
Fixes https://github.com/s-yadav/react-number-format/issues/295
=> Fix customInput typings

src/number_format.js
https://github.com/s-yadav/react-number-format/issues/293#issuecomment-510965743
=> resolves #293 - Calls clearTimeOut in onBlur function

test/library/input.spec.js
=> Implement onFocus prop tests

typings/number_format.d.ts
=> Fix type definition

src/number_format.js, src/utils.js, test/library/input.spec.js, webpack.config.js
=> Fix IOS numeric pad issue.

.travis.yml
=> Use node 14 for running travis

.github/PULL_REQUEST_TEMPLATE.md
=> chore: Add CSB Link and browsers to PR Template

.github/workflows/CI.yml, README.md
- Run gh-actions on push/pull-request event to master
=> CI: Run gh-actions on push/pull-request to master

package.json
=> Release 4.5.2 version bump

package.json
=> chore: Version bump

src/number_format.tsx, src/utils.tsx
=> Updated caret engine and boundary logic.

src/number_format_base.tsx, src/numeric_format.tsx, src/pattern_format.tsx, src/utils.tsx, test/library/keypress_and_caret.spec.js
=> Caret bugs fix

src/types.ts
=> add thousand value for thousandsGroupStyle property

documentation/v5/docusaurus.config.js
"Edit this page" link is wrong.
Updated docusaurus config
https://github.com/s-yadav/react-number-format/issues/775
=> Fix #775 - update `editUrl` for docusaurus

documentation/v5/docs/migration.md
Documentation MD change to mention customizable component accepting function value for format. Not knowing was a major friction item for me migrating from v4 -> v5.
https://github.com/s-yadav/react-number-format/discussions/716
=> Mention customization in migration.md

README.md, documentation/v5/docs/intro.md
Fix some typos and enhance descriptions on the main documentation page
=> [docs] Typo fixes and wording clarifications
